# Production configuration for GitHub Pages
# baseURL will be set automatically by GitHub Actions

# Fix URL canonicalization for production
canonifyURLs = false
relativeURLs = false
uglyURLs = false

# Enable Git info for production
enableGitInfo = true

# Additional production settings
minify = true
